targetNamespace: ''
parameters: {}
packages:
  - name: plant_diary
    environment:
      DO_SPACES_KEY: "${APP_DO_SPACES_KEY}"
      DO_SPACES_SECRET: "${APP_DO_SPACES_SECRET}"
      DATABASE_URL: "${APP_DATABASE_URL}"
    parameters: {}
    annotations: {}
    actions:
      - name: getImageCards
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        environment: {}
        annotations: {}
        limits: 
          timeout: 5000
      - name: getPost
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        environment: {}
        annotations: {}
        limits: 
          timeout: 5000
      - name: editPost
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        environment: {}
        annotations: {}
        limits: 
          timeout: 5000
      - name: getPostById
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        environment: {}
        annotations: {}
        limits: 
          timeout: 5000
      - name: getPosts
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        environment: {}
        annotations: {}
        limits: 
          timeout: 5000
