targetNamespace: ''
parameters: {}
packages:
  - name: plant_diary
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: getImageCards
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        environment: {}
        annotations: {}
        limits: 
          timeout: 5000
      - name: getPost
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        environment: {}
        annotations: {}
        limits: 
          timeout: 5000
      - name: editPost
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        environment: {}
        annotations: {}
        limits: 
          timeout: 5000
      - name: getPostById
        binary: false
        main: ''
        runtime: 'go:default'
        web: true
        environment: {}
        annotations: {}
        limits: 
          timeout: 5000
